apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-tigera.tem-bypass
spec:
  tier: allow-tigera
  order: 0
  selector: ''
  serviceAccountSelector: ''
  egress:
    - action: Allow
      protocol: TCP
      source: {}
      destination:
        ports:
          - '30925'
  types:
    - Egress
